# Generated by Django 5.1.6 on 2025-02-17 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-updated_at', 'name']},
        ),
        migrations.RenameField(
            model_name='account',
            old_name='full_name',
            new_name='name',
        ),
    ]
