# Generated by Django 5.1.6 on 2025-02-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='fas fa-folder', max_length=50),
        ),
    ]
